site_name: Advance JS Study Notes
site_url: http://advanced-js.shams-nahid.com/
site_description: Advance JS Study notes
site_author: Shams Nahid

repo_url: https://github.com/bmshamsnahid/Advance-JS-Study
edit_uri: ''

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2021 <a href="https://shams-nahid.com/">Shams Nahid</a>.
